MODEL:
  PRETRAIN_CHOICE: 'imagenet'
  METRIC_LOSS_TYPE: 'triplet'
  IF_LABELSMOOTH: 'on'
  IF_WITH_CENTER: 'no'
  NAME: 'ViT-B-16' # 'ViT-B-16' #更换骨干后，要换STRIDE_SIZE、SIZE_TRAIN、SIZE_TEST
  STRIDE_SIZE: [16, 16]
  ID_LOSS_WEIGHT : 0.25  # ID LOSS
  TRIPLET_LOSS_WEIGHT : 1.0 # Triplet LOSS
  I2T_LOSS_WEIGHT : 1.0 # i2t_ce_loss
  SIE_CAMERA: True
  SIE_VIEW: False
  SIE_COE : 1.0
  TSM_BETA_NUM: 10

INPUT:
  SIZE_TRAIN: [256, 128] #[256, 128] [252, 126] [336,128]
  SIZE_TEST: [256, 128]
  PROB: 0.5 # random horizontal flip
  RE_PROB: 0.5 # random erasing
  PADDING: 10
  PIXEL_MEAN: [0.485, 0.456, 0.406]
  PIXEL_STD: [0.229, 0.224, 0.225]

DATALOADER:
  SAMPLER: 'softmax_triplet'
  NUM_INSTANCE: 4
  NUM_WORKERS: 8
  SEQ_LEN: 8

SOLVER:
  STAGE1:
    IMS_PER_BATCH: 64
    OPTIMIZER_NAME: "Adam"
    BASE_LR: 0.00035
    WARMUP_LR_INIT: 0.00001
    LR_MIN: 1e-6
    WARMUP_METHOD: 'linear'
    WEIGHT_DECAY:  1e-4
    WEIGHT_DECAY_BIAS: 1e-4
    MAX_EPOCHS: 120
    CHECKPOINT_PERIOD: 120
    LOG_PERIOD: 50
    WARMUP_EPOCHS: 5
  
  STAGE2:
    IMS_PER_BATCH: 16
    OPTIMIZER_NAME: "Adam"
    BASE_LR: 0.00035 #0.000005
    WARMUP_METHOD: 'linear'
    WARMUP_ITERS: 10
    WARMUP_FACTOR: 0.1
    WEIGHT_DECAY:  0.0001
    WEIGHT_DECAY_BIAS: 0.0001
    LARGE_FC_LR: True
    LARGE_Prompt_LR: True
    MAX_EPOCHS: 40
    CHECKPOINT_PERIOD: 5 #5
    LOG_PERIOD: 50
    EVAL_PERIOD: 2
    BIAS_LR_FACTOR: 2
    
    STEPS: [10, 20, 30] #[30, 50, 70]
    GAMMA: 0.1
  
TEST:
  EVAL: False
  IMS_PER_BATCH: 1
  RE_RANKING: False
  WEIGHT: '/best_model.pth.tar'
  NECK_FEAT: 'before'
  FEAT_NORM: 'yes'
  ALL_FRAMES: False
  DISTANCE: 'cosine'
  SEQ_LEN: 16

DATASETS:
  NAMES: ('detreidx')
#  ROOT_DIR: ('/media/ycy/18b21f78-77a1-403a-959e-d65e937da92b/data/Mars')
  ROOT_DIR: ('/yqw/DATA/VReid-XFD/')

  # NAMES: ('ilidsvidsequence')
  # ROOT_DIR: ('../data/ilidsvidsequence/')
  
  # NAMES: ('lsvid')
  # ROOT_DIR: ('../data/LSVID')

OUTPUT_DIR: 'output_original/'
